FROM ruby:3.3.3-alpine

RUN apk add --no-cache \
  build-base \
  busybox \
  ca-certificates \
  curl \
  git \
  postgresql-dev \
  tzdata \
  vim
RUN mkdir -p /app
WORKDIR /app

EXPOSE 3000

# docker compose run web sh
#
# docker compose run web bundle install
# docker compose run web bundle exec rails db:create
# docker compose run web bundle exec rails db:schema:load
# docker compose run web bundle exec rails db:seed

CMD ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]